<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2019-09-08 12:10:32
 */
return [
    'base' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/static',
        'baseUrl' => '@web/static',
        'js' => [
            'base-01ec49c1e4ead2c4d249458598e36f6e.js',
        ],
        'css' => [
            'base-3d3897f276e51e9df441943255754e93.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'home' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/static',
        'baseUrl' => '@web/static',
        'js' => [
            'home-114548b8dea4472d51d25f41a8b80dd3.js',
        ],
        'css' => [
            'home-a12addca3dc62e15ca6a33926cf730d5.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'product' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/static',
        'baseUrl' => '@web/static',
        'js' => [
            'product-ba902a98fb0384d970162538a526994d.js',
        ],
        'css' => [
            'product-a9178e919d595f246f593baac1a55eb9.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'contact' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/static',
        'baseUrl' => '@web/static',
        'js' => [
            'contact-4dc426ebdea9160b5a8e7d443f069c29.js',
        ],
        'css' => [
            'contact-cb488d53c7832daf4db78dde82ecef88.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'frontend\\assets\\BaseAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'base',
        ],
    ],
    'frontend\\assets\\HomeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\BaseAsset',
            'home',
        ],
    ],
    'frontend\\assets\\ProductAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\BaseAsset',
            'product',
        ],
    ],
    'frontend\\assets\\ContactAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\BaseAsset',
            'contact',
        ],
    ],
];